# generated by datamodel-codegen:
#   filename:  hDAO_batch.json

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Extra


class HDAOBatchParameterItem(BaseModel):
    class Config:
        extra = Extra.forbid

    amount: str
    to_: str


class HDAOBatchParameter(BaseModel):
    __root__: List[HDAOBatchParameterItem]
