# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel


class Swaps(BaseModel):
    fa2: str
    issuer: str
    objkt_id: str
    xtz_per_objkt: str


class ObjktbidBidStorage(BaseModel):
    admin: str
    management_fee: str
    metadata: Dict[str, str]
    swap_id: str
    swaps: Dict[str, Swaps]
