# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, Extra


class SplitContractBStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    administrator: str
    coreParticipants: List[str]
    isPaused: bool
    marketplaceAddress: str
    minterAddress: str
    proposedAdministrator: Optional[str]
    registryAddress: str
    shares: Dict[str, str]
    tokenAddress: str
    totalShares: str
