# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class Auctions(BaseModel):
    class Config:
        extra = Extra.forbid

    artist: str
    creator: str
    end_price: str
    end_time: str
    fa2: str
    objkt_id: str
    royalties: str
    start_price: str
    start_time: str
    state: str


class ObjktbidDutchStorage(BaseModel):
    class Config:
        extra = Extra.forbid

    admin: str
    auction_id: str
    auctions: Dict[str, Auctions]
    management_fee: str
    metadata: Dict[str, str]
