# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel


class Asks(BaseModel):
    amount: str
    artist: str
    fa2: str
    issuer: str
    objkt_id: str
    royalties: str
    xtz_per_objkt: str


class Bids(BaseModel):
    artist: str
    fa2: str
    issuer: str
    objkt_id: str
    royalties: str
    xtz_per_objkt: str


class ObjktbidMarketplaceStorage(BaseModel):
    admin: str
    ask_id: str
    asks: Dict[str, Asks]
    bid_id: str
    bids: Dict[str, Bids]
    management_fee: str
    metadata: Dict[str, str]
