# generated by datamodel-codegen:
#   filename:  conclude_auction.json

from __future__ import annotations

from pydantic import BaseModel


class ConcludeAuctionParameter(BaseModel):
    __root__: str
