# generated by datamodel-codegen:
#   filename:  create_auction.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class CreateAuctionParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    artist: str
    end_time: str
    extension_time: str
    fa2: str
    objkt_id: str
    price_increment: str
    reserve: str
    royalties: str
    start_time: str
