# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class Swaps(BaseModel):
    class Config:
        extra = Extra.forbid

    creator: str
    issuer: str
    objkt_amount: str
    objkt_id: str
    royalties: str
    xtz_per_objkt: str


class HenSwapV2Storage(BaseModel):
    class Config:
        extra = Extra.forbid

    counter: str
    fee: str
    manager: str
    metadata: Dict[str, str]
    objkt: str
    swaps: Dict[str, Swaps]
