# generated by datamodel-codegen:
#   filename:  claim_hDAO.json

from __future__ import annotations

from pydantic import BaseModel


class ClaimHDAOParameter(BaseModel):
    hDAO_amount: str
    objkt_id: str
