# generated by datamodel-codegen:
#   filename:  configure.json

from __future__ import annotations

from pydantic import BaseModel


class ConfigureParameter(BaseModel):
    fa2: str
    protocol: str
