# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel


class SplitContractAStorage(BaseModel):
    administrator: str
    hicetnuncMinterAddress: str
    shares: Dict[str, str]
    totalShares: str
