# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict, List

from pydantic import BaseModel


class SplitContractAStorage(BaseModel):
    administrator: str
    coreParticipants: List[str]
    hicetnuncMinterAddress: str
    shares: Dict[str, int]
    totalShares: str
