# generated by datamodel-codegen:
#   filename:  create_auction.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class CreateAuctionParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    artist: str
    end_price: str
    end_time: str
    fa2: str
    objkt_id: str
    royalties: str
    start_price: str
    start_time: str
