# generated by datamodel-codegen:
#   filename:  registry.json

from __future__ import annotations

from pydantic import BaseModel, Extra


class RegistryParameter(BaseModel):
    class Config:
        extra = Extra.forbid

    metadata: str
    subjkt: str
