# generated by datamodel-codegen:
#   filename:  storage.json

from __future__ import annotations

from typing import Dict

from pydantic import BaseModel, Extra


class Swaps(BaseModel):
    class Config:
        extra = Extra.forbid

    creator: str
    fa2: str
    issuer: str
    objkt_amount: str
    objkt_id: str
    royalties: str
    xtz_per_objkt: str


class HenSwapV3Storage(BaseModel):
    class Config:
        extra = Extra.forbid

    allowed_fa2s: Dict[str, bool]
    counter: str
    fee: str
    fee_recipient: str
    manager: str
    metadata: Dict[str, str]
    paused: bool
    swaps: Dict[str, Swaps]
