# generated by datamodel-codegen:
#   filename:  ask.json

from __future__ import annotations

from pydantic import BaseModel


class AskParameter(BaseModel):
    fa2: str
    objkt_id: str
    price: str
