# generated by datamodel-codegen:
#   filename:  bid.json

from __future__ import annotations

from pydantic import BaseModel


class BidParameter(BaseModel):
    artist: str
    fa2: str
    objkt_id: str
    royalties: str
