# generated by datamodel-codegen:
#   filename:  fulfill_ask.json

from __future__ import annotations

from pydantic import BaseModel


class FulfillAskParameter(BaseModel):
    amount: str
    ask_id: str
